services:
  app:
    image: ${DOCKERHUB_USERNAME}/guttok_app:latest
    container_name: guttok_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/${DOCKER_MYSQL_DATABASE}
      - MYSQL_USERNAME=${DOCKER_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${DOCKER_REDIS_PASSWORD}
    volumes:
      - ./app/data:/data
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: guttok_mysql
    restart: always
    ports:
      - "13306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      TZ: ${DOCKER_TZ}
    command: [ "--character-set-server=${DOCKER_MYSQL_CHARSET}", "--collation-server=${DOCKER_MYSQL_COLLATION}" ]
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DOCKER_MYSQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0
    container_name: guttok_redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: [ "sh", "-c", "redis-server --requirepass ${DOCKER_REDIS_PASSWORD}" ]
    environment:
      TZ: ${DOCKER_TZ}
    volumes:
      - ./db/redis/data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${DOCKER_REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
